[versions]
slf4j-version = "2.0.1"
log4j2-version = "2.18.0"
log4j2-slf4j-version = "2.18.0"
picocli-version = "4.6.3"
jackson-version = "2.13.4"
jetbrains-annotations-version = "23.0.0"
metadata-extractor-version = "2.18.0"
pointlocation6709-version = "4.2.1"
unirest-version = "4.0.0-RC2"

shadow-version = "7.1.2"
names-version = "0.42.0"
lombok-version = "6.5.1"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
metadataExtractor = { group = "com.drewnoakes", name = "metadata-extractor", version.ref = "metadata-extractor-version" }
pointLocation = { group = "us.fatehi", name = "pointlocation6709", version.ref = "pointlocation6709-version" }
unirest = { group = "com.konghq", name = "unirest-java", version.ref = "unirest-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-version" }
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-version" }
