name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - uses: actions/cache@v3
        name: Cache gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check build
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: shadow-jar
          path: build/libs/filesecure-shaded.jar

  dropbox:
    runs-on: ubuntu-latest
    needs: build
    if: contains('refs/heads/main', github.ref)
    steps:
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: shadow-jar
      - name: Deploy on Dropbox
        uses: deka0106/upload-to-dropbox@v2.0.1
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_DEPLOY_TOKEN }}
          src: "filesecure-shaded.jar"
          dest: "/Documents/JARs/FileSecure.jar"
          mode: overwrite
